#!/usr/bin/env bash
# Format the C/C++ sources with clang-format (Google style, see .clang-format).
#
#   tools/format.sh           rewrite in place
#   tools/format.sh --check   fail if anything is unformatted (for CI)
set -euo pipefail
cd "$(dirname "$0")/.."

# crates/host-capi/include/watoots.h is generated by cbindgen and carries its
# own style; reformatting it would be undone by the next build.
files=()
while IFS= read -r f; do
  case "$f" in
    crates/host-capi/include/watoots.h) continue ;;
    # Generated by wit-bindgen on every build, and gitignored; formatting it
    # would be undone by the next `tools/build-plugins.sh cpp cpp-asset`.
    examples/plugins/cpp-lint/bindings/*) continue ;;
    examples/plugins/cpp-asset/bindings/*) continue ;;
  esac
  files+=("$f")
done < <(
  git ls-files --cached --others --exclude-standard \
    '*.c' '*.h' '*.cc' '*.hpp')
if [ "${#files[@]}" -eq 0 ]; then
  echo "no C/C++ sources to format"
  exit 0
fi

# LLVM 22 is the pinned major (ADR-0003): `BasedOnStyle: Google` is not frozen
# across releases, so an unpinned clang-format is a source of spurious red. Any
# 22 will do -- versioned package, Homebrew keg, or an explicit CLANG_FORMAT.
fmt=${CLANG_FORMAT:-}
if [ -z "$fmt" ]; then
  for candidate in \
    /opt/homebrew/opt/llvm@22/bin/clang-format \
    /usr/local/opt/llvm@22/bin/clang-format \
    /usr/lib/llvm-22/bin/clang-format \
    "$(command -v clang-format-22 2>/dev/null || true)" \
    "$(command -v clang-format 2>/dev/null || true)"; do
    if [ -n "$candidate" ] && [ -x "$candidate" ]; then
      fmt=$candidate
      break
    fi
  done
fi
if [ -z "$fmt" ] || ! command -v "$fmt" >/dev/null 2>&1; then
  echo "clang-format not found (brew install llvm@22)" >&2
  exit 1
fi

case "$("$fmt" --version)" in
  *"clang-format version 22."*) ;;
  *)
    echo "warning: $fmt is $("$fmt" --version)," >&2
    echo "         but CI pins LLVM 22; formatting may disagree." >&2
    ;;
esac

if [ "${1:-}" = "--check" ]; then
  "$fmt" --dry-run --Werror "${files[@]}"
else
  "$fmt" -i "${files[@]}"
fi
