// NOLINTBEGIN(readability-identifier-naming, modernize-use-using,
//             modernize-macro-to-enum, cppcoreguidelines-macro-to-enum,
//             cppcoreguidelines-use-enum-class, performance-enum-size)
// This file is C, and the checks above are C++-only advice a C ABI header
// cannot take. Naming is `wt_` snake_case per ADR-0001 rather than the Google
// C++ naming that watoots.hpp follows.

#ifndef WATOOTS_H_
#define WATOOTS_H_

// Generated by cbindgen from crates/host-capi/src/lib.rs. Do not edit by hand:
// `cargo build -p watoots-capi` rewrites this file in place.


#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>

// Status codes. Zero is success.
typedef enum wt_status {
  WT_OK = 0,
  WT_ERR_INVALID_ARGUMENT = 1,
  WT_ERR_NOT_FOUND = 2,
  WT_ERR_MANIFEST = 3,
  WT_ERR_PERMISSION_DENIED = 4,
  WT_ERR_LOAD = 5,
  WT_ERR_TRAP = 6,
  WT_ERR_LIMIT_EXCEEDED = 7,
  WT_ERR_INTERNAL = 8,
  WT_ERR_SIGNATURE_INVALID = 9,
} wt_status;

// Severity of a `wasi:logging` message.
//
// The six cases and their order are `wasi:logging@0.1.0-draft`'s own, so the
// numeric values are stable for as long as that proposal's `enum level` is.
typedef enum wt_log_level {
  WT_LOG_TRACE = 0,
  WT_LOG_DEBUG = 1,
  WT_LOG_INFO = 2,
  WT_LOG_WARN = 3,
  WT_LOG_ERROR = 4,
  WT_LOG_CRITICAL = 5,
} wt_log_level;

// Which authorisation decision an audit event describes.
//
// The values are stable. A new decision is appended rather than inserted, for
// the same reason [`wt_status`]'s are fixed: a C host switching on this must
// not have its arms silently re-point.
typedef enum wt_audit_kind {
  // A plugin was compiled, granted and instantiated.
  WT_AUDIT_LOADED = 0,
  // A load was refused; the plugin never ran.
  WT_AUDIT_LOAD_REFUSED = 1,
  // One import's verdict, as the grant check resolved it.
  WT_AUDIT_IMPORT = 2,
  // A plugin's code was replaced.
  WT_AUDIT_RELOADED = 3,
  // A reload was refused; the plugin is still running its old code.
  WT_AUDIT_RELOAD_REFUSED = 4,
  // A `wasi:logging` line passed the manifest's level ceiling.
  WT_AUDIT_LOG_ADMITTED = 5,
  // A `wasi:logging` line was dropped by it.
  WT_AUDIT_LOG_SUPPRESSED = 6,
  // A `[limits]` ceiling was spent.
  WT_AUDIT_CEILING_SPENT = 7,
} wt_audit_kind;

// How one import resolved at load.
//
// Three of the four read as "allowed", and only `WT_AUDIT_GRANTED` is a
// capability the manifest handed out.
typedef enum wt_audit_verdict {
  // The manifest covers it, or it is WASI plumbing that needs no grant.
  WT_AUDIT_GRANTED = 0,
  // The manifest does not, so the load is refused.
  WT_AUDIT_DENIED = 1,
  // The application declared it serves this interface itself.
  WT_AUDIT_HOST_PROVIDED = 2,
  // Imported only for its types: nothing there is callable.
  WT_AUDIT_TYPES_ONLY = 3,
} wt_audit_verdict;

// Which `[limits]` ceiling was spent.
typedef enum wt_ceiling {
  // `limits.fuel`.
  WT_CEILING_FUEL = 0,
  // `limits.timeout`.
  WT_CEILING_TIMEOUT = 1,
  // `limits.memory`. The only one a plugin never sees as an error: a refused
  // growth makes `memory.grow` answer -1 and the call carries on.
  WT_CEILING_MEMORY = 2,
  // `limits.transfer`.
  WT_CEILING_TRANSFER = 3,
  // `limits.log_bytes`.
  WT_CEILING_LOG_BYTES = 4,
  // `limits.log_messages`.
  WT_CEILING_LOG_MESSAGES = 5,
} wt_ceiling;

// Whether a profile row describes an export or an import.
typedef enum wt_function_kind {
  // A function the component exports, entered through [`wt_plugin_call`].
  WT_FUNCTION_EXPORT = 0,
  // A function the host serves and the component imported.
  WT_FUNCTION_IMPORT = 1,
} wt_function_kind;

// An error: a status code and a message.
typedef struct wt_error_t wt_error_t;

// Builder for a host. Consumed by [`wt_host_builder_build`].
typedef struct wt_host_builder_t wt_host_builder_t;

// A configured host.
typedef struct wt_host_t wt_host_t;

// A loaded plugin.
typedef struct wt_plugin_t wt_plugin_t;

// A function the application serves to plugins.
//
// `args` holds `args_len` WAVE strings. Write at most one WAVE string to
// `result_out` — allocate it with [`wt_string_new`] — or leave it untouched if
// the function returns nothing. On failure, return a non-zero status and
// optionally set `*error_out` with [`wt_error_new`].
//
// The callback and `userdata` must be safe to use from any thread: watoots
// does not serialise calls into it.
typedef enum wt_status (*wt_host_func_t)(void *userdata,
                                         const char *const *args,
                                         size_t args_len,
                                         char **result_out,
                                         struct wt_error_t **error_out);

// Where a plugin's `wasi:logging` messages go.
//
// `context` and `message` are NUL-terminated, borrowed for the duration of the
// call, and **untrusted**: they come from the plugin. Copy what you keep, and
// never pass either to a `printf`-family format argument.
//
// There is no timestamp parameter. A guest-supplied one would defeat the
// pinned wall clock and make a recording unreplayable, and a host-supplied one
// would only be a worse version of the stamp your own logging framework
// applies. Stamp it in the sink.
//
// Returns nothing: `wasi:logging`'s `log` has no result, so there is no
// failure for a guest to observe. The sink and `userdata` must be safe to use
// from any thread, and must not throw — watoots does not serialise calls into
// it, and unwinding across the boundary is undefined behaviour.
typedef void (*wt_log_sink_t)(void *userdata,
                              enum wt_log_level level,
                              const char *context,
                              const char *message);

// One authorisation decision, as structured fields.
//
// Every string is NUL-terminated and **borrowed for the duration of the
// callback** — copy what you keep. A field that does not apply to this event's
// `kind` is NULL for a string, and unspecified for a number or an enum: read
// the `kind` first. The field list below says which kinds set what.
//
// **No field here carries an argument value or a log message body.** That is
// the whole reason this is not a `wt_trace_event_t`: an audit line has to be
// safe to keep and to paste into an issue, and a trace is the thing that is
// not. See ADR-0011.
typedef struct wt_audit_event_t {
  // Which decision this is. Read it before anything else.
  enum wt_audit_kind kind;
  // The plugin the decision is about. Never NULL.
  const char *plugin;
  // SHA-256 of the component bytes, lowercase hex. Set for the load and
  // reload kinds, NULL otherwise. The same digest a recorded trace names its
  // component by.
  const char *sha256;
  // The import this decision is about, exactly as the component declares it.
  // Always set for `WT_AUDIT_IMPORT`; set on a refusal when an import decided
  // it, and NULL on a refusal that no import decided.
  const char *import;
  // What that import needs, e.g. `"network"`. NULL when `import` is.
  const char *requirement;
  // The manifest key an operator would edit for it, e.g.
  // `"permissions.net"`. NULL when `import` is.
  const char *grant_key;
  // Why a load or reload was refused. NULL for every other kind. May contain
  // newlines; the rendered line passed alongside carries only the first.
  const char *reason;
  // The manifest key of the ceiling that was spent, e.g. `"limits.fuel"`.
  // NULL unless `kind` is `WT_AUDIT_CEILING_SPENT`.
  const char *limit_key;
  // How the import resolved. `WT_AUDIT_IMPORT` only.
  enum wt_audit_verdict verdict;
  // Which ceiling. `WT_AUDIT_CEILING_SPENT` only.
  enum wt_ceiling ceiling;
  // The level the plugin logged at. The log kinds only, and only when
  // `level_known`.
  enum wt_log_level level;
  // False when the guest named a `level` case this build does not define,
  // which is dropped rather than delivered so a manifest's ceiling holds
  // across a revision of the proposal. The log kinds only.
  bool level_known;
  // The manifest's level ceiling, which is what dropped the line.
  // `WT_AUDIT_LOG_SUPPRESSED` only.
  enum wt_log_level ceiling_level;
  // How many imports the component declares. `WT_AUDIT_LOADED` only.
  uint64_t imports;
  // Reloads this plugin has survived, this one included.
  // `WT_AUDIT_RELOADED` only.
  uint64_t reloads;
} wt_audit_event_t;

// Observes every authorisation decision the host makes.
//
// `line` is the whole event rendered as one line — what a C host forwards to
// its own logger without unpacking anything. `event` is the same decision as
// structured fields, for a host that wants to match on it. Both are borrowed
// for the duration of the call, and so is everything `event` points at.
//
// **Nothing is installed by default.** An application that never calls
// [`wt_host_builder_audit_hook`] gets no audit trail; see `docs/SECURITY.md`.
//
// Returns nothing: a decision has already been made by the time it is
// reported, and there is nothing here for a hook to veto. It must be safe to
// use from any thread and must not throw — watoots does not serialise calls
// into it, and unwinding across the boundary is undefined behaviour.
typedef void (*wt_audit_hook_t)(void *userdata,
                                const char *line,
                                const struct wt_audit_event_t *event);

// What the host has observed about a plugin since it was loaded.
//
// Plain integers, owned by the caller: there is nothing to free. Every field
// is measured at the boundary rather than reported by the guest, so a plugin
// can neither forge nor inflate them. See ADR-0006 for why watoots offers
// these and not metrics a plugin emits about itself.
//
// Every counter **accumulates across a reload** — these answer "what has this
// plugin cost me", and a reload is a new build of the same plugin rather than
// a new plugin. [`wt_plugin_profile`] takes the opposite decision for the
// opposite reason; see ADR-0010.
typedef struct wt_plugin_stats_t {
  // Calls that have completed, successfully or not.
  uint64_t calls;
  // Fuel burned across those calls; zero when the manifest meters none.
  uint64_t fuel_consumed;
  // Largest linear memory the guest was granted, in bytes.
  uint64_t peak_memory_bytes;
  // `wasi:logging` messages emitted.
  uint64_t log_messages;
  // Bytes of log message emitted.
  uint64_t log_bytes;
  // Imports the component declares. The *current* bytes': a reload re-runs
  // the check, so this describes what is running now.
  uint64_t imports_declared;
  // How many of those the manifest did not grant.
  uint64_t imports_denied;
  // Successful [`wt_plugin_reload`]s. Every other field here accumulates
  // across those; see the note on the struct.
  uint64_t reloads;
} wt_plugin_stats_t;

// What one reload did with the outgoing instance's state.
//
// Plain integers and flags, owned by the caller: there is nothing to free. The
// reload itself either happened or returned a non-`WT_OK` status; this says
// what crossed. `state_saved` without `state_restored` means the outgoing
// build had state to hand over and the incoming one declared nowhere to put
// it, so it was dropped — not an error, since a rollback to a build without
// the hooks has to keep working, but worth a line in a log.
typedef struct wt_reload_report_t {
  // The outgoing instance exported `save-state` and it returned.
  bool state_saved;
  // The incoming instance exported `restore-state` and was given the value.
  bool state_restored;
  // Reloads this plugin has survived, this one included.
  uint64_t reloads;
} wt_reload_report_t;

// Where a plugin's time has gone, split at the host/guest boundary.
//
// Plain integers, owned by the caller: there is nothing to free. `guest_nanos`
// and `host_nanos` are measured from the exact transitions the engine reports;
// `marshalling_nanos` is **derived** — it is what is left of `wall_nanos`
// after the other two, so it holds the canonical ABI's copying *and* watoots'
// own dispatch overhead. Read it as "not accounted for elsewhere" rather than
// as a measurement of copying. See ADR-0009.
//
// `host_nanos` counts every host call, the `wasi:` interfaces included, but
// only the host functions watoots installed itself get a row, so the rows do
// not add up to the bucket.
typedef struct wt_plugin_profile_t {
  // Calls through [`wt_plugin_call`] that have completed.
  uint64_t calls;
  // Wall time spent inside those calls.
  uint64_t wall_nanos;
  // Of that, time executing wasm, host calls made from it excluded.
  uint64_t guest_nanos;
  // Of that, time inside host functions the guest called.
  uint64_t host_nanos;
  // What is left. A remainder, not a measurement.
  uint64_t marshalling_nanos;
  // Of that, time turning WAVE text into values and back.
  //
  // Every call through this C API pays it — `wt_plugin_call` takes text, so
  // there is no other path. Separate from `marshalling_nanos` because it is
  // a separate decision: marshalling is what the component model costs, this
  // is what the untyped path costs.
  uint64_t wave_nanos;
  // How many rows [`wt_plugin_profile_function`] will serve.
  uint64_t function_count;
} wt_plugin_profile_t;

// One per-WIT-function row of a profile.
//
// `iface` and `func` are **borrowed**: they point into the plugin and stay
// valid until the next [`wt_plugin_profile`] on it or until the plugin is
// deleted. Copy what you keep. `iface` is `""` for an export, which
// [`wt_plugin_call`] names without an interface.
//
// An import row carries only `host_nanos`, with `wall_nanos` equal to it:
// watoots times the host function but sees no boundary of its own inside it.
typedef struct wt_function_profile_t {
  // Export or import.
  enum wt_function_kind kind;
  // Interface name, version included; `""` for an export. Borrowed.
  const char *iface;
  // The function's own name. Borrowed.
  const char *func;
  // How many times it was entered.
  uint64_t calls;
  // Wall time across those entries.
  uint64_t wall_nanos;
  // Time inside wasm, host calls made from it excluded. Zero for an import.
  uint64_t guest_nanos;
  // Time inside host functions.
  uint64_t host_nanos;
  // The remainder. Zero for an import.
  uint64_t marshalling_nanos;
  // Of that, WAVE text conversion. Zero for an import.
  uint64_t wave_nanos;
} wt_function_profile_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Library version, e.g. `"0.0.0"`. Never NULL; static storage.
const char *wt_version_string(void);

// Stable spelling of a status code, e.g. `"WT_ERR_MANIFEST"`. Never NULL.
const char *wt_status_name(enum wt_status status);

// The `wasi:logging` spelling of a level, e.g. `"warn"`. Never NULL.
const char *wt_log_level_name(enum wt_log_level level);

// Stable spelling of an audit decision, e.g. `"log-suppressed"`. Never NULL.
//
// The same word that leads the rendered line, so a log written from the
// structured fields and one written from the line agree.
const char *wt_audit_kind_name(enum wt_audit_kind kind);

// Stable spelling of an import verdict, e.g. `"host-provided"`. Never NULL.
const char *wt_audit_verdict_name(enum wt_audit_verdict verdict);

// The manifest key a ceiling is set by, e.g. `"limits.fuel"`. Never NULL.
const char *wt_ceiling_name(enum wt_ceiling ceiling);

// Copy a C string into one watoots owns, for returning from a host function.
//
// Returns NULL if `text` is NULL or contains a NUL byte.
char *wt_string_new(const char *text);

// Free a string produced by this library. NULL is ignored.
void wt_string_delete(char *text);

// Build an error to return from a host function.
struct wt_error_t *wt_error_new(enum wt_status code, const char *message);

// Free an error. NULL is ignored.
void wt_error_delete(struct wt_error_t *error);

// The error's status code.
enum wt_status wt_error_code(const struct wt_error_t *error);

// The error's message. Borrowed; valid until the error is deleted.
const char *wt_error_message(const struct wt_error_t *error);

// Start building a host.
struct wt_host_builder_t *wt_host_builder_new(void);

// Free a builder that was never built. NULL is ignored.
void wt_host_builder_delete(struct wt_host_builder_t *builder);

// Read the manifest from a TOML file.
enum wt_status wt_host_builder_manifest_from_file(struct wt_host_builder_t *builder,
                                                  const char *path,
                                                  struct wt_error_t **error_out);

// Set the manifest from TOML text.
enum wt_status wt_host_builder_manifest_from_string(struct wt_host_builder_t *builder,
                                                    const char *toml,
                                                    struct wt_error_t **error_out);

// Define a `${name}` substitution for manifest paths.
enum wt_status wt_host_builder_var(struct wt_host_builder_t *builder,
                                   const char *name,
                                   const char *value,
                                   struct wt_error_t **error_out);

// Cache compiled components under this directory. Must be a trusted path:
// entries are machine code loaded without re-validation, so write access to it
// is equivalent to code execution in this process. There is no default.
//
// A host already reuses a component it compiled earlier in the same run, so
// this is what makes the *first* load of the next run cheap. That matters for
// a large guest — an interpreter-based plugin can take seconds to compile —
// and barely at all for a small one.
enum wt_status wt_host_builder_cache_dir(struct wt_host_builder_t *builder,
                                         const char *dir,
                                         struct wt_error_t **error_out);

// Declare that the application serves this interface without supplying it.
enum wt_status wt_host_builder_provide_interface(struct wt_host_builder_t *builder,
                                                 const char *iface,
                                                 struct wt_error_t **error_out);

// Serve one function of one interface to plugins.
//
// `interface` must be spelled as the component imports it, version included.
enum wt_status wt_host_builder_host_func(struct wt_host_builder_t *builder,
                                         const char *iface,
                                         const char *func,
                                         wt_host_func_t implementation,
                                         void *userdata,
                                         struct wt_error_t **error_out);

// Receive the plugin's `wasi:logging` messages.
//
// Whether the interface links at all is the manifest's decision, not this one:
// `permissions.logging` grants it and sets the level ceiling, and a component
// importing `wasi:logging` under a manifest that says nothing fails to load
// however many sinks are registered. Calling this twice replaces the first
// sink; there is one, and watoots does no fan-out.
//
// `userdata` must outlive the host built from this builder.
enum wt_status wt_host_builder_log_sink(struct wt_host_builder_t *builder,
                                        wt_log_sink_t sink,
                                        void *userdata,
                                        struct wt_error_t **error_out);

// Observe every authorisation decision: what a plugin was permitted to do, and
// what it was refused.
//
// The sibling of a trace recorder and deliberately not the same hook. A trace
// answers *what happened* and carries the argument values to prove it; this
// answers *what was allowed*, and carries names and verdicts only — which is
// what makes an audit line safe to keep and to paste into an issue. A
// suppressed log line is reported as a suppression at a level; the line itself
// is not in it. See ADR-0011.
//
// The callback gets both a rendered line and the structured fields, because
// forwarding one to your logger and matching on the other are different jobs
// and neither should have to reconstruct the other.
//
// **Off unless you call this.** An application that installs no hook gets no
// audit trail — not a default one written somewhere. Calling this twice
// replaces the first hook; there is one, and watoots does no fan-out.
//
// `userdata` must outlive the host built from this builder.
enum wt_status wt_host_builder_audit_hook(struct wt_host_builder_t *builder,
                                          wt_audit_hook_t hook,
                                          void *userdata,
                                          struct wt_error_t **error_out);

// Split every plugin's time into guest, host-call and marshalling.
//
// Opt-in, because a call hook then fires on every host/guest transition. Read
// the result with [`wt_plugin_profile`]. Refused alongside a trace recorder:
// profiling changes timing, so a session recorded under it would not
// reproduce — [`wt_host_builder_build`] reports that as
// `WT_ERR_INVALID_ARGUMENT`.
enum wt_status wt_host_builder_profile(struct wt_host_builder_t *builder,
                                       struct wt_error_t **error_out);

// Also sample guest stacks every `interval_ms`, for a Firefox Profiler JSON.
//
// Implies [`wt_host_builder_profile`], and adds the half of the answer the
// boundary buckets cannot give: which *guest* function is hot. Write the
// result with [`wt_plugin_write_guest_profile`].
//
// Sampling is driven from the same epoch deadline that enforces
// `limits.timeout`, and **the timeout wins**: the interval is clamped to what
// is left of the budget, so profiling a runaway plugin does not keep it alive.
// An interval of zero is rejected; anything under a millisecond samples once
// per millisecond, which is the epoch granularity.
enum wt_status wt_host_builder_profile_guest_samples(struct wt_host_builder_t *builder,
                                                     uint64_t interval_ms,
                                                     struct wt_error_t **error_out);

// Build the host. The builder is consumed but must still be freed with
// [`wt_host_builder_delete`].
enum wt_status wt_host_builder_build(struct wt_host_builder_t *builder,
                                     struct wt_host_t **host_out,
                                     struct wt_error_t **error_out);

// Free a host. NULL is ignored.
void wt_host_delete(struct wt_host_t *host);

// Load a component from a file.
enum wt_status wt_host_load(const struct wt_host_t *host,
                            const char *path,
                            struct wt_plugin_t **plugin_out,
                            struct wt_error_t **error_out);

// Load a component already in memory.
enum wt_status wt_host_load_binary(const struct wt_host_t *host,
                                   const char *name,
                                   const uint8_t *wasm,
                                   size_t wasm_len,
                                   struct wt_plugin_t **plugin_out,
                                   struct wt_error_t **error_out);

// Load a component from memory together with the signature that vouches for it.
//
// `signature` is base64, as `cosign sign-blob --output-signature` writes it,
// and is checked against the manifest's `signature.keys` before the component
// is compiled. When the manifest lists no keys the argument is ignored rather
// than rejected, so a caller may pass one unconditionally.
//
// Fails with `WT_ERR_SIGNATURE_INVALID` if no trusted key verifies the bytes.
enum wt_status wt_host_load_binary_signed(const struct wt_host_t *host,
                                          const char *name,
                                          const uint8_t *wasm,
                                          size_t wasm_len,
                                          const uint8_t *signature,
                                          size_t signature_len,
                                          struct wt_plugin_t **plugin_out,
                                          struct wt_error_t **error_out);

// Describe what a component would be granted, without instantiating it.
//
// Answers "what can this plugin do", resolved against the manifest: a granted
// filesystem names its directories, an interface the application must serve is
// listed separately from a denial, and a capability granted but never imported
// is reported. For the raw per-import list, see [`wt_host_inspect_imports`].
//
// Writes a human-readable report to `report_out`; free it with
// [`wt_string_delete`].
enum wt_status wt_host_inspect(const struct wt_host_t *host,
                               const uint8_t *wasm,
                               size_t wasm_len,
                               char **report_out,
                               struct wt_error_t **error_out);

// Every import and its decision, one per line.
//
// The detail behind [`wt_host_inspect`]. Free `report_out` with
// [`wt_string_delete`].
enum wt_status wt_host_inspect_imports(const struct wt_host_t *host,
                                       const uint8_t *wasm,
                                       size_t wasm_len,
                                       char **report_out,
                                       struct wt_error_t **error_out);

// Check that a component implements a world.
//
// `wt_host_inspect` answers "does this plugin ask for anything it should not";
// this answers "does it provide what I am about to call". `wit` is a path to a
// WIT file, a directory containing one, or a wasm-encoded WIT package. `world`
// may be NULL when the package declares exactly one.
//
// Returns `WT_OK` when the component conforms, and `WT_ERR_LOAD` with a
// message naming the world when it does not.
enum wt_status wt_host_check_targets(const struct wt_host_t *host,
                                     const uint8_t *wasm,
                                     size_t wasm_len,
                                     const char *wit,
                                     const char *world,
                                     struct wt_error_t **error_out);

// Free a plugin. NULL is ignored.
void wt_plugin_delete(struct wt_plugin_t *plugin);

// The plugin's name. Borrowed; valid until the plugin is deleted.
const char *wt_plugin_name(const struct wt_plugin_t *plugin);

// Read a plugin's counters into `stats_out`.
enum wt_status wt_plugin_stats(const struct wt_plugin_t *plugin,
                               struct wt_plugin_stats_t *stats_out,
                               struct wt_error_t **error_out);

// The export a plugin uses to hand its state out before it is replaced.
//
// `"save-state"`. Never NULL; static storage. It takes no parameters and
// returns exactly one value of whatever type the world declares — watoots
// carries the value without interpreting it. Optional: a component that does
// not export it reloads with no state.
const char *wt_save_state_export(void);

// The export a plugin uses to take state back after it replaces another.
//
// `"restore-state"`. One parameter, of the type `save-state` returns, and no
// result. Also optional. Never NULL; static storage.
const char *wt_restore_state_export(void);

// Replace a plugin's code with new bytes, keeping its name and its handle.
//
// Reload is `wt_host_load` plus a state handoff, **not** a cheaper path that
// skips the checks: the bytes are compiled and intersected with the same
// manifest, and a component asking for something the manifest does not grant
// is refused here with `WT_ERR_PERMISSION_DENIED` exactly as it would be at
// load. New bytes must not acquire a capability by arriving as an update.
//
// **A failed reload leaves the plugin running the code it was already
// running.** The replacement is built to completion — compiled, checked,
// instantiated and given the state — before it takes over, so every failure
// returns with the handle still valid and still usable. The one exception is
// a trap inside `save-state`: Wasmtime refuses to re-enter a component
// instance after any trap, so that plugin is unreplaced but also uncallable.
//
// If the outgoing instance exports `save-state` its value is passed to the
// incoming instance's `restore-state`; both are optional, and a missing one
// means the reload carries no state rather than failing. The value crosses as
// a typed WIT value, so it is bounded by `limits.transfer` like any other
// crossing and its type must match on both sides.
//
// `report_out` may be NULL. Counters from `wt_plugin_stats` carry across;
// `wt_plugin_profile` starts again, and sampled guest profiles do not survive
// at all — call `wt_plugin_write_guest_profile` first if you want them. Rows
// already fetched with `wt_plugin_profile` stay readable across a reload and
// go on describing the build they were taken from, until the next
// `wt_plugin_profile` replaces them.
enum wt_status wt_plugin_reload(struct wt_plugin_t *plugin,
                                const uint8_t *wasm,
                                size_t wasm_len,
                                struct wt_reload_report_t *report_out,
                                struct wt_error_t **error_out);

// Replace a plugin's code with a component the signature vouches for.
//
// As [`wt_plugin_reload`], with the same check `wt_host_load_binary_signed`
// runs. A reload re-verifies deliberately: the moment the code changes is the
// moment publisher identity matters most, and a replacement that does not
// verify is refused before the running instance is entered.
enum wt_status wt_plugin_reload_signed(struct wt_plugin_t *plugin,
                                       const uint8_t *wasm,
                                       size_t wasm_len,
                                       const uint8_t *signature,
                                       size_t signature_len,
                                       struct wt_reload_report_t *report_out,
                                       struct wt_error_t **error_out);

// Replace a plugin's code with a component read from `path`.
//
// As [`wt_plugin_reload`], and additionally re-points `${plugin_dir}` at the
// directory the replacement came from. The plugin keeps the name it was loaded
// under even when the file is named differently: a reload replaces code, not
// identity.
enum wt_status wt_plugin_reload_file(struct wt_plugin_t *plugin,
                                     const char *path,
                                     struct wt_reload_report_t *report_out,
                                     struct wt_error_t **error_out);

// Read a plugin's time split into `profile_out`.
//
// Takes a mutable plugin because it also refreshes the per-function rows that
// [`wt_plugin_profile_function`] serves, which invalidates the `iface` and
// `func` pointers from any earlier call.
//
// Fails with `WT_ERR_INVALID_ARGUMENT` when the host was not built with
// [`wt_host_builder_profile`]: a page of zeroes is a worse answer than being
// told the feature is off.
enum wt_status wt_plugin_profile(struct wt_plugin_t *plugin,
                                 struct wt_plugin_profile_t *profile_out,
                                 struct wt_error_t **error_out);

// Read one row of the profile most recently taken by [`wt_plugin_profile`].
//
// `index` is below that call's `function_count`. The `iface` and `func`
// pointers are borrowed from the plugin and are invalidated by the next
// [`wt_plugin_profile`] on it.
enum wt_status wt_plugin_profile_function(const struct wt_plugin_t *plugin,
                                          uint64_t index,
                                          struct wt_function_profile_t *function_out,
                                          struct wt_error_t **error_out);

// Write the sampled guest profile to `path`, as Firefox Profiler JSON.
//
// Needs [`wt_host_builder_profile_guest_samples`]. The profiler is consumed:
// sampling stops here and a second call fails. Load the file at
// <https://profiler.firefox.com/>.
enum wt_status wt_plugin_write_guest_profile(struct wt_plugin_t *plugin,
                                             const char *path,
                                             struct wt_error_t **error_out);

// Call an exported function with WAVE-encoded arguments.
//
// On success `*result_out` is either NULL, when the function returns nothing,
// or a WAVE string to free with [`wt_string_delete`].
enum wt_status wt_plugin_call(struct wt_plugin_t *plugin,
                              const char *export_,
                              const char *const *args,
                              size_t args_len,
                              char **result_out,
                              struct wt_error_t **error_out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* WATOOTS_H_ */

// NOLINTEND(readability-identifier-naming, modernize-use-using,
//           modernize-macro-to-enum, cppcoreguidelines-macro-to-enum,
//           cppcoreguidelines-use-enum-class, performance-enum-size)
