#ifndef WATOOTS_H_
#define WATOOTS_H_

// Scaffolding. The real C surface is an M3 deliverable and will be generated by
// cbindgen from crates/host-capi; what is declared here exists so the build,
// format, tidy, and test pipeline has something to run against, and so the
// shape of the boundary (opaque handles, status codes, message strings) is
// fixed before any of it is written.

// NOLINTBEGIN(readability-identifier-naming, modernize-use-using,
//             modernize-macro-to-enum, cppcoreguidelines-macro-to-enum,
//             cppcoreguidelines-use-enum-class, performance-enum-size)
// This file is C, and the checks above are C++-only advice that a C ABI header
// cannot take: `using` and `enum class` do not exist here, the version macros
// must stay macros so they work in #if, and narrowing the enum's base type
// would change the ABI. Naming is `wt_` snake_case per ADR-0001 rather than the
// Google C++ naming watoots.hpp follows. This is the one file that opts out;
// everything else in .clang-tidy still applies.

#define WATOOTS_VERSION_MAJOR 0
#define WATOOTS_VERSION_MINOR 0
#define WATOOTS_VERSION_PATCH 0

#if defined(_WIN32) && defined(WATOOTS_SHARED)
#if defined(WATOOTS_BUILDING)
#define WT_API __declspec(dllexport)
#else
#define WT_API __declspec(dllimport)
#endif
#else
#define WT_API
#endif

#ifdef __cplusplus
extern "C" {
#endif

// Status codes crossing the boundary. WT_OK is success; every other value is
// accompanied by a message owned by the call that produced it. Provisional:
// M3 fixes the final set once the host library has real failure modes.
typedef enum wt_status {
  WT_OK = 0,
  WT_ERR_INVALID_ARGUMENT = 1,
  WT_ERR_NOT_FOUND = 2,
  WT_ERR_MANIFEST = 3,
  WT_ERR_PERMISSION_DENIED = 4,
  WT_ERR_LOAD = 5,
  WT_ERR_TRAP = 6,
  WT_ERR_LIMIT_EXCEEDED = 7,
  WT_ERR_INTERNAL = 8
} wt_status;

// Opaque handles. Ownership is explicit: every wt_*_new has a wt_*_delete, and
// wt::internal::OwnedHandle in watoots.hpp is the C++ side of that contract.
typedef struct wt_host wt_host_t;

// Library version, e.g. "0.0.0". Never NULL; static storage duration.
WT_API const char* wt_version_string(void);

// Stable spelling of a status code, e.g. "WT_ERR_MANIFEST". Never NULL; static
// storage duration. Unknown codes yield "WT_ERR_INTERNAL".
WT_API const char* wt_status_name(wt_status status);

#ifdef __cplusplus
}  // extern "C"
#endif

// NOLINTEND(readability-identifier-naming, modernize-use-using,
//           modernize-macro-to-enum, cppcoreguidelines-macro-to-enum,
//           cppcoreguidelines-use-enum-class, performance-enum-size)

#endif  // WATOOTS_H_
