// NOLINTBEGIN(readability-identifier-naming, modernize-use-using,
//             modernize-macro-to-enum, cppcoreguidelines-macro-to-enum,
//             cppcoreguidelines-use-enum-class, performance-enum-size)
// This file is C, and the checks above are C++-only advice a C ABI header
// cannot take. Naming is `wt_` snake_case per ADR-0001 rather than the Google
// C++ naming that watoots.hpp follows.

#ifndef WATOOTS_H_
#define WATOOTS_H_

// Generated by cbindgen from crates/host-capi/src/lib.rs. Do not edit by hand:
// `cargo build -p watoots-capi` rewrites this file in place.


#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>

// Status codes. Zero is success.
typedef enum wt_status {
  WT_OK = 0,
  WT_ERR_INVALID_ARGUMENT = 1,
  WT_ERR_NOT_FOUND = 2,
  WT_ERR_MANIFEST = 3,
  WT_ERR_PERMISSION_DENIED = 4,
  WT_ERR_LOAD = 5,
  WT_ERR_TRAP = 6,
  WT_ERR_LIMIT_EXCEEDED = 7,
  WT_ERR_INTERNAL = 8,
} wt_status;

// Severity of a `wasi:logging` message.
//
// The six cases and their order are `wasi:logging@0.1.0-draft`'s own, so the
// numeric values are stable for as long as that proposal's `enum level` is.
typedef enum wt_log_level {
  WT_LOG_TRACE = 0,
  WT_LOG_DEBUG = 1,
  WT_LOG_INFO = 2,
  WT_LOG_WARN = 3,
  WT_LOG_ERROR = 4,
  WT_LOG_CRITICAL = 5,
} wt_log_level;

// An error: a status code and a message.
typedef struct wt_error_t wt_error_t;

// Builder for a host. Consumed by [`wt_host_builder_build`].
typedef struct wt_host_builder_t wt_host_builder_t;

// A configured host.
typedef struct wt_host_t wt_host_t;

// A loaded plugin.
typedef struct wt_plugin_t wt_plugin_t;

// A function the application serves to plugins.
//
// `args` holds `args_len` WAVE strings. Write at most one WAVE string to
// `result_out` — allocate it with [`wt_string_new`] — or leave it untouched if
// the function returns nothing. On failure, return a non-zero status and
// optionally set `*error_out` with [`wt_error_new`].
//
// The callback and `userdata` must be safe to use from any thread: watoots
// does not serialise calls into it.
typedef enum wt_status (*wt_host_func_t)(void *userdata,
                                         const char *const *args,
                                         size_t args_len,
                                         char **result_out,
                                         struct wt_error_t **error_out);

// Where a plugin's `wasi:logging` messages go.
//
// `context` and `message` are NUL-terminated, borrowed for the duration of the
// call, and **untrusted**: they come from the plugin. Copy what you keep, and
// never pass either to a `printf`-family format argument.
//
// There is no timestamp parameter. A guest-supplied one would defeat the
// pinned wall clock and make a recording unreplayable, and a host-supplied one
// would only be a worse version of the stamp your own logging framework
// applies. Stamp it in the sink.
//
// Returns nothing: `wasi:logging`'s `log` has no result, so there is no
// failure for a guest to observe. The sink and `userdata` must be safe to use
// from any thread, and must not throw — watoots does not serialise calls into
// it, and unwinding across the boundary is undefined behaviour.
typedef void (*wt_log_sink_t)(void *userdata,
                              enum wt_log_level level,
                              const char *context,
                              const char *message);

// What the host has observed about a plugin since it was loaded.
//
// Plain integers, owned by the caller: there is nothing to free. Every field
// is measured at the boundary rather than reported by the guest, so a plugin
// can neither forge nor inflate them. See ADR-0006 for why watoots offers
// these and not metrics a plugin emits about itself.
typedef struct wt_plugin_stats_t {
  // Calls that have completed, successfully or not.
  uint64_t calls;
  // Fuel burned across those calls; zero when the manifest meters none.
  uint64_t fuel_consumed;
  // Largest linear memory the guest was granted, in bytes.
  uint64_t peak_memory_bytes;
  // `wasi:logging` messages emitted.
  uint64_t log_messages;
  // Bytes of log message emitted.
  uint64_t log_bytes;
  // Imports the component declares.
  uint64_t imports_declared;
  // How many of those the manifest did not grant.
  uint64_t imports_denied;
} wt_plugin_stats_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Library version, e.g. `"0.0.0"`. Never NULL; static storage.
const char *wt_version_string(void);

// Stable spelling of a status code, e.g. `"WT_ERR_MANIFEST"`. Never NULL.
const char *wt_status_name(enum wt_status status);

// The `wasi:logging` spelling of a level, e.g. `"warn"`. Never NULL.
const char *wt_log_level_name(enum wt_log_level level);

// Copy a C string into one watoots owns, for returning from a host function.
//
// Returns NULL if `text` is NULL or contains a NUL byte.
char *wt_string_new(const char *text);

// Free a string produced by this library. NULL is ignored.
void wt_string_delete(char *text);

// Build an error to return from a host function.
struct wt_error_t *wt_error_new(enum wt_status code, const char *message);

// Free an error. NULL is ignored.
void wt_error_delete(struct wt_error_t *error);

// The error's status code.
enum wt_status wt_error_code(const struct wt_error_t *error);

// The error's message. Borrowed; valid until the error is deleted.
const char *wt_error_message(const struct wt_error_t *error);

// Start building a host.
struct wt_host_builder_t *wt_host_builder_new(void);

// Free a builder that was never built. NULL is ignored.
void wt_host_builder_delete(struct wt_host_builder_t *builder);

// Read the manifest from a TOML file.
enum wt_status wt_host_builder_manifest_from_file(struct wt_host_builder_t *builder,
                                                  const char *path,
                                                  struct wt_error_t **error_out);

// Set the manifest from TOML text.
enum wt_status wt_host_builder_manifest_from_string(struct wt_host_builder_t *builder,
                                                    const char *toml,
                                                    struct wt_error_t **error_out);

// Define a `${name}` substitution for manifest paths.
enum wt_status wt_host_builder_var(struct wt_host_builder_t *builder,
                                   const char *name,
                                   const char *value,
                                   struct wt_error_t **error_out);

// Cache compiled components under this directory. Must be a trusted path.
enum wt_status wt_host_builder_cache_dir(struct wt_host_builder_t *builder,
                                         const char *dir,
                                         struct wt_error_t **error_out);

// Declare that the application serves this interface without supplying it.
enum wt_status wt_host_builder_provide_interface(struct wt_host_builder_t *builder,
                                                 const char *iface,
                                                 struct wt_error_t **error_out);

// Serve one function of one interface to plugins.
//
// `interface` must be spelled as the component imports it, version included.
enum wt_status wt_host_builder_host_func(struct wt_host_builder_t *builder,
                                         const char *iface,
                                         const char *func,
                                         wt_host_func_t implementation,
                                         void *userdata,
                                         struct wt_error_t **error_out);

// Receive the plugin's `wasi:logging` messages.
//
// Whether the interface links at all is the manifest's decision, not this one:
// `permissions.logging` grants it and sets the level ceiling, and a component
// importing `wasi:logging` under a manifest that says nothing fails to load
// however many sinks are registered. Calling this twice replaces the first
// sink; there is one, and watoots does no fan-out.
//
// `userdata` must outlive the host built from this builder.
enum wt_status wt_host_builder_log_sink(struct wt_host_builder_t *builder,
                                        wt_log_sink_t sink,
                                        void *userdata,
                                        struct wt_error_t **error_out);

// Build the host. The builder is consumed but must still be freed with
// [`wt_host_builder_delete`].
enum wt_status wt_host_builder_build(struct wt_host_builder_t *builder,
                                     struct wt_host_t **host_out,
                                     struct wt_error_t **error_out);

// Free a host. NULL is ignored.
void wt_host_delete(struct wt_host_t *host);

// Load a component from a file.
enum wt_status wt_host_load(const struct wt_host_t *host,
                            const char *path,
                            struct wt_plugin_t **plugin_out,
                            struct wt_error_t **error_out);

// Load a component already in memory.
enum wt_status wt_host_load_binary(const struct wt_host_t *host,
                                   const char *name,
                                   const uint8_t *wasm,
                                   size_t wasm_len,
                                   struct wt_plugin_t **plugin_out,
                                   struct wt_error_t **error_out);

// Describe what a component would be granted, without instantiating it.
//
// Answers "what can this plugin do", resolved against the manifest: a granted
// filesystem names its directories, an interface the application must serve is
// listed separately from a denial, and a capability granted but never imported
// is reported. For the raw per-import list, see [`wt_host_inspect_imports`].
//
// Writes a human-readable report to `report_out`; free it with
// [`wt_string_delete`].
enum wt_status wt_host_inspect(const struct wt_host_t *host,
                               const uint8_t *wasm,
                               size_t wasm_len,
                               char **report_out,
                               struct wt_error_t **error_out);

// Every import and its decision, one per line.
//
// The detail behind [`wt_host_inspect`]. Free `report_out` with
// [`wt_string_delete`].
enum wt_status wt_host_inspect_imports(const struct wt_host_t *host,
                                       const uint8_t *wasm,
                                       size_t wasm_len,
                                       char **report_out,
                                       struct wt_error_t **error_out);

// Check that a component implements a world.
//
// `wt_host_inspect` answers "does this plugin ask for anything it should not";
// this answers "does it provide what I am about to call". `wit` is a path to a
// WIT file, a directory containing one, or a wasm-encoded WIT package. `world`
// may be NULL when the package declares exactly one.
//
// Returns `WT_OK` when the component conforms, and `WT_ERR_LOAD` with a
// message naming the world when it does not.
enum wt_status wt_host_check_targets(const struct wt_host_t *host,
                                     const uint8_t *wasm,
                                     size_t wasm_len,
                                     const char *wit,
                                     const char *world,
                                     struct wt_error_t **error_out);

// Free a plugin. NULL is ignored.
void wt_plugin_delete(struct wt_plugin_t *plugin);

// The plugin's name. Borrowed; valid until the plugin is deleted.
const char *wt_plugin_name(const struct wt_plugin_t *plugin);

// Read a plugin's counters into `stats_out`.
enum wt_status wt_plugin_stats(const struct wt_plugin_t *plugin,
                               struct wt_plugin_stats_t *stats_out,
                               struct wt_error_t **error_out);

// Call an exported function with WAVE-encoded arguments.
//
// On success `*result_out` is either NULL, when the function returns nothing,
// or a WAVE string to free with [`wt_string_delete`].
enum wt_status wt_plugin_call(struct wt_plugin_t *plugin,
                              const char *export_,
                              const char *const *args,
                              size_t args_len,
                              char **result_out,
                              struct wt_error_t **error_out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* WATOOTS_H_ */

// NOLINTEND(readability-identifier-naming, modernize-use-using,
//           modernize-macro-to-enum, cppcoreguidelines-macro-to-enum,
//           cppcoreguidelines-use-enum-class, performance-enum-size)
